
package web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransactionSoap", targetNamespace = "http://web/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransactionSoap {


    /**
     * 
     * @param arg0
     * @return
     *     returns web.GroupOfTransaction
     */
    @WebMethod
    @WebResult(name = "GroupOfTransaction", partName = "GroupOfTransaction")
    @Action(input = "http://web/TransactionSoap/findAllByTypeRequest", output = "http://web/TransactionSoap/findAllByTypeResponse")
    public GroupOfTransaction findAllByType(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
