
package org.example.web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransactionSoap", targetNamespace = "http://web.example.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransactionSoap {


    /**
     * 
     * @param string
     * @return
     *     returns org.example.web.Transaction
     */
    @WebMethod
    @WebResult(name = "User", partName = "User")
    @Action(input = "http://web.example.org/TransactionSoap/callfindAllByDateAndUsernameRequest", output = "http://web.example.org/TransactionSoap/callfindAllByDateAndUsernameResponse")
    public Transaction callfindAllByDateAndUsername(
        @WebParam(name = "String", partName = "String")
        String string);

    /**
     * 
     * @return
     *     returns org.example.web.GroupOfTransaction
     */
    @WebMethod
    @WebResult(name = "GroupOfTransaction", partName = "GroupOfTransaction")
    @Action(input = "http://web.example.org/TransactionSoap/readAllTransactionsRequest", output = "http://web.example.org/TransactionSoap/readAllTransactionsResponse")
    public GroupOfTransaction readAllTransactions();

    /**
     * 
     * @param string
     * @return
     *     returns org.example.web.GroupOfTransaction
     */
    @WebMethod
    @WebResult(name = "GroupOfTransaction", partName = "GroupOfTransaction")
    @Action(input = "http://web.example.org/TransactionSoap/readAllByUsernameRequest", output = "http://web.example.org/TransactionSoap/readAllByUsernameResponse")
    public GroupOfTransaction readAllByUsername(
        @WebParam(name = "String", partName = "String")
        String string);

    /**
     * 
     * @param user
     */
    @WebMethod
    @Action(input = "http://web.example.org/TransactionSoap/callFindAllTransactionRequest", output = "http://web.example.org/TransactionSoap/callFindAllTransactionResponse")
    public void callFindAllTransaction(
        @WebParam(name = "User", partName = "User")
        Transaction user);

    /**
     * 
     * @param string
     * @return
     *     returns org.example.web.Transaction
     */
    @WebMethod
    @WebResult(name = "Username", partName = "Username")
    @Action(input = "http://web.example.org/TransactionSoap/callFindByUsernameRequest", output = "http://web.example.org/TransactionSoap/callFindByUsernameResponse")
    public Transaction callFindByUsername(
        @WebParam(name = "String", partName = "String")
        String string);

}
