//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.08 at 03:49:29 PM IST 
//


package links.debitcard;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for debitCard complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="debitCard">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="debitCardNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="debitCardCvv" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="debitCardPin" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="debitCardExpiry" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="debitCardStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="domesticLimit" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="internationalLimit" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "debitCard", propOrder = {
    "debitCardNumber",
    "accountNumber",
    "customerId",
    "debitCardCvv",
    "debitCardPin",
    "debitCardExpiry",
    "debitCardStatus",
    "domesticLimit",
    "internationalLimit"
})
public class DebitCard {

    protected long debitCardNumber;
    protected long accountNumber;
    @XmlElement(required = true)
    protected BigInteger customerId;
    @XmlElement(required = true)
    protected BigInteger debitCardCvv;
    @XmlElement(required = true)
    protected BigInteger debitCardPin;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar debitCardExpiry;
    @XmlElement(required = true)
    protected String debitCardStatus;
    protected double domesticLimit;
    protected double internationalLimit;

    /**
     * Gets the value of the debitCardNumber property.
     * 
     */
    public long getDebitCardNumber() {
        return debitCardNumber;
    }

    /**
     * Sets the value of the debitCardNumber property.
     * 
     */
    public void setDebitCardNumber(long value) {
        this.debitCardNumber = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     */
    public long getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     */
    public void setAccountNumber(long value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustomerId(BigInteger value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the debitCardCvv property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDebitCardCvv() {
        return debitCardCvv;
    }

    /**
     * Sets the value of the debitCardCvv property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDebitCardCvv(BigInteger value) {
        this.debitCardCvv = value;
    }

    /**
     * Gets the value of the debitCardPin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDebitCardPin() {
        return debitCardPin;
    }

    /**
     * Sets the value of the debitCardPin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDebitCardPin(BigInteger value) {
        this.debitCardPin = value;
    }

    /**
     * Gets the value of the debitCardExpiry property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDebitCardExpiry() {
        return debitCardExpiry;
    }

    /**
     * Sets the value of the debitCardExpiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDebitCardExpiry(XMLGregorianCalendar value) {
        this.debitCardExpiry = value;
    }

    /**
     * Gets the value of the debitCardStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitCardStatus() {
        return debitCardStatus;
    }

    /**
     * Sets the value of the debitCardStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitCardStatus(String value) {
        this.debitCardStatus = value;
    }

    /**
     * Gets the value of the domesticLimit property.
     * 
     */
    public double getDomesticLimit() {
        return domesticLimit;
    }

    /**
     * Sets the value of the domesticLimit property.
     * 
     */
    public void setDomesticLimit(double value) {
        this.domesticLimit = value;
    }

    /**
     * Gets the value of the internationalLimit property.
     * 
     */
    public double getInternationalLimit() {
        return internationalLimit;
    }

    /**
     * Sets the value of the internationalLimit property.
     * 
     */
    public void setInternationalLimit(double value) {
        this.internationalLimit = value;
    }

}
